import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ChevronLeft } from 'lucide-react';
import { Card, Chip, Etichetta, Titolo } from '../components/ui';
import { cardioZones, cardioZonesNote, phases, programPrinciples, workouts } from '../data/program';
import { exerciseName } from '../data/exercises';
import { vaiA } from '../lib/router';
export default function Program() {
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("button", { type: "button", className: "btn-vetro", onClick: () => vaiA(''), children: [_jsx(ChevronLeft, { size: 18 }), " Oggi"] }), _jsx(Titolo, { sub: "24 sessioni, 3 fasi da 4 settimane", children: "Il tuo programma" }), phases.map((f) => (_jsxs(Card, { children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs(Etichetta, { children: ["Fase ", f.id, " \u00B7 ", f.name] }), _jsx(Chip, { tono: "scuro", children: f.rir })] }), _jsx("p", { className: "mt-1 text-[15px]", children: f.goal }), _jsxs("p", { className: "soft mt-1 text-sm", children: ["Sessioni ", f.sessions[0], "\u2013", f.sessions[1]] }), _jsx("div", { className: "mt-3 space-y-2", children: workouts
                            .filter((w) => w.phase === f.id)
                            .map((w) => (_jsxs("div", { className: "rounded-2xl bg-white/55 p-3 dark:bg-white/[0.07]", children: [_jsx("p", { className: "font-display text-base font-extrabold", children: w.title }), _jsx("ul", { className: "soft mt-1 space-y-0.5 text-sm", children: w.strength.map((s, i) => (_jsxs("li", { className: "flex justify-between gap-3", children: [_jsx("span", { className: "truncate", children: exerciseName(s.exerciseId) }), _jsxs("span", { className: "cifre shrink-0 font-semibold", children: [s.sets, "\u00D7", s.reps ?? `${s.durationSec}"`, s.perSide ? '/lato' : ''] })] }, i))) }), _jsxs("p", { className: "soft mt-1 text-xs", children: ["Core: ", w.core.rounds, " giri \u00B7 Cardio:", ' ', exerciseName(w.cardio.exerciseId), " ", w.cardio.totalMin, "\u2032", ' ', w.cardio.type === 'liss' ? 'zona 2' : 'a intervalli'] })] }, w.id))) })] }, f.id))), _jsxs(Card, { children: [_jsx(Etichetta, { children: "Come funziona" }), _jsx("div", { className: "mt-2 space-y-3", children: programPrinciples.map((p) => (_jsxs("div", { children: [_jsx("p", { className: "font-display text-base font-extrabold", children: p.title }), _jsx("p", { className: "mt-0.5 text-[15px] leading-relaxed", children: p.body })] }, p.title))) })] }), _jsxs(Card, { children: [_jsx(Etichetta, { children: "Zone di intensit\u00E0 cardio" }), _jsx("div", { className: "mt-2 space-y-2", children: cardioZones.map((z) => (_jsxs("div", { className: "rounded-2xl bg-white/55 p-3 dark:bg-white/[0.07]", children: [_jsx("p", { className: "font-display text-base font-extrabold", children: z.zone }), _jsx("p", { className: "text-[15px]", children: z.feel }), _jsxs("p", { className: "soft text-sm", children: ["RPE ", z.rpe, " \u00B7 FC ", z.hr] })] }, z.zone))) }), _jsx("p", { className: "soft mt-2 text-xs leading-relaxed", children: cardioZonesNote })] })] }));
}
