import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Check, CircleHelp, History as HistoryIcon } from 'lucide-react';
import { Card, Chip, Etichetta, InfoTermine, Stepper } from './ui';
import ExerciseSheet from './ExerciseSheet';
import { GLOSSARY } from '../data/tips';
export default function ExerciseCard({ item, exercise, etichetta, sets, suggestion, lastTime, step, onChange, onComplete, }) {
    const [spiegazione, setSpiegazione] = useState(false);
    const aTempo = typeof item.durationSec === 'number' && !item.reps;
    const senzaCarico = suggestion.action === 'corpo-libero';
    return (_jsxs(Card, { className: "space-y-3", children: [_jsxs("div", { className: "flex items-start gap-3", children: [_jsx("span", { className: "flex h-8 min-w-8 shrink-0 items-center justify-center rounded-xl bg-inchiostro px-2 text-sm font-extrabold text-giallo dark:bg-giallo dark:text-inchiostro", children: etichetta }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("h3", { className: "font-display text-lg font-extrabold leading-tight", children: exercise.name }), _jsx("p", { className: "soft text-sm", children: exercise.muscles.join(' · ') })] })] }), _jsxs("div", { className: "flex flex-wrap items-center gap-1.5", children: [_jsxs(Chip, { tono: "scuro", children: [sets.length, " \u00D7 ", item.reps ?? `${item.durationSec}"`, item.perSide ? ' per lato' : ''] }), item.restSec > 0 ? _jsxs(Chip, { children: ["Rec ", item.restSec, "\""] }) : _jsx(Chip, { children: "Superserie" }), item.rir ? (_jsxs("span", { className: "inline-flex items-center rounded-full bg-black/[0.07] pl-2.5 text-xs font-bold dark:bg-white/10", children: ["RIR ", item.rir, _jsx(InfoTermine, { termine: "RIR", testo: GLOSSARY.rir })] })) : null] }), item.notes ? _jsx("p", { className: "soft text-sm", children: item.notes }) : null, item.perSide ? (_jsxs("p", { className: "text-sm font-bold", children: ["Attenzione: le ripetizioni sono ", item.reps, " per lato / per gamba."] })) : null, _jsxs("button", { type: "button", className: "btn-vetro w-full", onClick: () => setSpiegazione(true), children: [_jsx(CircleHelp, { size: 18 }), " Come si esegue"] }), _jsxs("div", { className: "rounded-2xl bg-black/[0.05] p-3 text-sm dark:bg-white/[0.07]", children: [_jsx(Etichetta, { children: "Peso suggerito" }), _jsx("p", { className: "mt-0.5 leading-snug", children: suggestion.message }), lastTime ? (_jsxs("p", { className: "soft mt-1 flex items-center gap-1.5 text-[13px]", children: [_jsx(HistoryIcon, { size: 13 }), " ", lastTime] })) : null] }), _jsx("ul", { className: "space-y-2", children: sets.map((s, i) => (_jsxs("li", { className: `rounded-2xl p-2.5 transition ${s.completed ? 'bg-inchiostro/[0.08] dark:bg-giallo/15' : 'bg-white/55 dark:bg-white/[0.06]'}`, children: [_jsxs("div", { className: "flex items-center justify-between gap-2", children: [_jsxs("span", { className: "text-sm font-extrabold", children: ["Serie ", i + 1] }), _jsxs("button", { type: "button", onClick: () => onComplete(i), "aria-pressed": s.completed, className: `btn min-h-[44px] px-4 text-sm ${s.completed
                                        ? 'bg-inchiostro text-giallo dark:bg-giallo dark:text-inchiostro'
                                        : 'bg-white/80 dark:bg-white/10'}`, children: [_jsx(Check, { size: 16 }), " ", s.completed ? 'Fatta' : 'Completato'] })] }), _jsxs("div", { className: "mt-2 flex flex-wrap items-end gap-3", children: [!senzaCarico ? (_jsxs("label", { className: "block", children: [_jsx("span", { className: "etichetta", children: "Peso" }), _jsx("div", { className: "mt-1", children: _jsx(Stepper, { value: s.weightKg, step: step, max: 300, suffix: "kg", onChange: (v) => onChange(i, { weightKg: v }) }) })] })) : null, _jsxs("label", { className: "block", children: [_jsx("span", { className: "etichetta", children: aTempo ? 'Secondi' : 'Ripetizioni' }), _jsx("div", { className: "mt-1", children: _jsx(Stepper, { value: aTempo ? s.durationSec : s.reps, step: aTempo ? 5 : 1, max: aTempo ? 600 : 60, onChange: (v) => onChange(i, aTempo ? { durationSec: v } : { reps: v }) }) })] })] })] }, i))) }), spiegazione ? (_jsx(ExerciseSheet, { exercise: exercise, onClose: () => setSpiegazione(false) })) : null] }));
}
